config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/users/:id/trackers', to: 'users#activity_trackers'
  resources :users
  resources :charities
  resources :pledges 
  resources :groups
  resources :challenges
  resources :activity_trackers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity_tracker.rb
class ActivityTracker < ApplicationRecord
    belongs_to :user
    belongs_to :challenge
end

app/controllers/activity_trackers_controller.rb
class ActivityTrackersController < ApplicationController
    before_action :authenticate!, except: [:index, :show]

    def index
        @activity_trackers = ActivityTracker.all
    end

    

    def new
        @activity_tracker = ActivityTracker.new
        @challenges = Challenge.all
    end

    def create 
        @activity_tracker = current_user.activity_trackers.build(activity_tracker_params)
        if @activity_tracker.save 
            redirect_to challenge_path(@activity_tracker.challenge)
        else  
            render :new 
        end 
    end 

    def edit
        @activity_tracker = ActivityTracker.find(params[:id])
    end

    def update 
        @activity_tracker = ActivityTracker.find(params[:id])
        if @activity_tracker.update(activity_tracker_params)
            redirect_to activity_tracker_path(@activity_tracker)
        else
            render :edit
        end 
    end 
    
    
    def destroy
        @activity_tracker = ActivityTracker.find(params[:id])
        @activity_tracker.destroy
        redirect_to activity_trackers_path(@activity_tracker)
    end 

    private 

    def activity_tracker_params 
        params.require(:activity_tracker).permit(:user_id, :challenge_id, :day, :user_reps)
    end 

end

app/helpers/activity_trackers_helper.rb
module ActivityTrackersHelper
end

app/views/activity_trackers/_form.html.erb
<%= form_for(@activity_tracker) do |f| %>
  <div class="field">
    <%= f.label :day %>
    <%= f.select :day, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %>
    <%= f.label "Challenge" %>
    <%= f.collection_select(:challenge_id, Challenge.all, :id, :name) %>
    <%= f.label :user_reps %>
    <%= f.number_field :user_reps %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_trackers/edit.html.erb
<h1>Edit Your Tracker</h1>

<%= render("form") %>

<h2><%= link_to 'Back', activity_trackers_path %></h2>

app/views/activity_trackers/index.html.erb
<h1> All User-Challenge Activity Trackers </h1>

<table>
  <thead>
    <tr>
      <th><h2>Name</h2></th>
      <th><h2>Challenge</h2></th>
      
      
      
    </tr>
  </thead>

  <tbody>
    <% @activity_trackers.each do |activity_tracker| %>
      <tr>
        
        <td><%= link_to(activity_tracker.user.name, user_path(activity_tracker.user)) %></td>
        <td><%= link_to(activity_tracker.challenge.name, challenge_path(activity_tracker.challenge)) %></td>
        <br>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<h2><%= link_to 'Add a Tracker for a Challenge', new_activity_tracker_path %></h2>
<br>
<br>

<h2><%= link_to("All Users", users_path) %></h2>
<h2><%= link_to('All Challenges', challenges_path) %></h2>

app/views/activity_trackers/new.html.erb
<h1>Create a New Tracker</h1>
<div class="w3-container">
  <h2 class="w3-center w3-animate-top">Crush This Workout!</h2>
</div>

<%= render("form") %>

<h2><%= link_to 'Back', activity_trackers_path %></h2>

app/views/activity_trackers/show.html.erb
<h1> TEST </h1>

<p>
<strong>Days: </strong>
<%= @activity_tracker.user.days %>
</p>
<br>
<p>
<strong>Reps: </strong>
<%= @activity_tracker.user.user_reps %>
<% end %>
</p>
<br>
<p>
      <strong>Challenge</strong>
      
</p>
  <br>
  <p>   
      <strong>This Weeks's Activity Rep Goal</strong>
<%= @activity_tracker.challenge.activity_rep %>
    </p>
     