config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/users/:id/trackers', to: 'users#activity_trackers'
  resources :users
  resources :charities
  resources :pledges 
  resources :groups
  resources :challenges
  resources :activity_trackers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :challenges
    has_many :charities, through: :challenges
    has_many :users

    validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :authenticate!, except: [:index, :show]
    def index
        @groups = Group.all
    end

    def show
        @group = Group.find(params[:id])
    end

    def new
        @group = Group.new
    end
    

    def create 
        @group = Group.create(group_params)
        
            if @group.save 
                redirect_to group_path(@group)
            else 
                render :new
            end 
    end

    def edit 
        @group = Group.find(params[:id])
    end 

    def update 
        @group = Group.find(params[:id])
        if @group.update(group_params)
            redirect_to group_path(@group)
        else
            render :edit
        end 
    end 
    
    def destroy 
        @group = Group.find(params[:id])
        @group.destroy
        redirect_to groups_path
    end 

    private 

    def group_params 
        params.require(:group).permit(:name)
    end 


    
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<strong>Edit a Group</strong>

<%= render("form") %>

app/views/groups/index.html.erb
<h1>All Groups</h1>


<table>
  <thead>
    <tr>
      <th><h2>Name</h2></th>
    
      
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to(group.name, group_path(group)) %></td>
        
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to('New Group', new_group_path) %></h2>

app/views/groups/new.html.erb
<h1><strong>Create a New Group</strong></h1>

<%= render("form") %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>



<ul>
  <% @group.users.each do |user| %>
    <li><%= link_to(user.name, user_path(user)) %></li>
  <% end %>
</ul>

<h2><%= link_to('All Groups', groups_path) %> |


<%= link_to("Edit", edit_group_path(@group)) %></h2>