config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/users/:id/trackers', to: 'users#activity_trackers'
  resources :users
  resources :charities
  resources :pledges 
  resources :groups
  resources :challenges
  resources :activity_trackers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :pledges
    has_many :charities, through: :pledges
    belongs_to :group
    has_many :activity_trackers
    has_many :challenges, through: :activity_trackers


    validates :username, presence: true, uniqueness: true, :on => :create
    validates :password, presence: true, length: { minimum: 4}


    def days 
       self.activity_trackers.map{|tracker| tracker.day}
    end

    def reps 
      self.activity_trackers.map{|tracker| tracker.user_reps}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate!, except: [:index, :new, :create]
    def index 
        @users = User.all 
    end  

    def new
        @user = User.new
        @groups = Group.all
    end

    def show
        @user = User.find(params[:id])
    end
    
    


    def create 
        @user = User.new(user_params)
        
            if @user.save 
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else 
                render :new
            end 
    end

    def edit 
        @user = User.find(params[:id])
    end 

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end 
    end 


    def destroy 
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end 

    private 

    def user_params 
        params.require(:user).permit(:name, :username, :password, :age, :height, :weight, :group_id)
    end 


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>
<%= form.label "Join A Group" %>
  <%= form.collection_select(:group_id, Group.all, :id, :name) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render('form') %>

<h2><%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %></h2>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Age</th>
      <th>Height</th>
      <th>Weight</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to(user.name, user_path(user)) %></td>
        <td><%= user.username %></td>
        <td><%= user.age %></td>
        <td><%= user.height %></td>
        <td><%= user.weight %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to('New User', new_user_path) %></h2>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<h2><%= link_to 'Back', users_path %></h2>

app/views/users/show.html.erb
<h1>Welcome to Push-Up</h1>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Height:</strong>
  <%= @user.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @user.weight %>
</p>

<p>
  <strong>Group:</strong>
  <%= link_to(@user.group.name, group_path(@user.group)) %>
</p>
<h2><%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %></h2>