config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/users/:id/trackers', to: 'users#activity_trackers'
  resources :users
  resources :charities
  resources :pledges 
  resources :groups
  resources :challenges
  resources :activity_trackers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    belongs_to :charity 
    belongs_to :group
    has_many :activity_trackers
    has_many :users, through: :activity_trackers
    validates :name, presence: true
    validates :charity_id, presence: true
    validates :group_id, presence: true
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
    before_action :authenticate!, except: [:index, :show]

    def index
        @challenges  = Challenge.all
    end

    def show
        @challenge = Challenge.find(params[:id])
    end

    def new
        @challenge  = Challenge.new
        @charities = Charity.all
        @groups = Group.all
    end

    def create 
        @challenge = current_user.group.challenges.build(challenge_params)
        if @challenge.save 
            redirect_to challenge_path(@challenge)
        else  
            render :new 
        end 
    end 

    def edit
        @challenge = Challenge.find(params[:id])
    end

    def update 
        @challenge = Challenge.find(params[:id])
        if @challenge.update(challenge_params)
            redirect_to challenge_path(@challenge)
        else
            render :edit
        end 
    end 
    
    
    def destroy
        @challenge = Challenge.find(params[:id])
        @challenge.destroy
        redirect_to challenges_path
    end 

    private 

    def challenge_params 
        params.require(:challenge).permit(:name, :activity, :activity_reps, :start_date, :end_date, :group_id, :charity_id)
    end 
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :activity %>
    <%= f.text_field :activity %>
    <br>
    <%= f.label :activity_reps %>
    <%= f.text_field :activity_reps %>
    <br>
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
    <br>
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
    <br>
    <%= f.collection_select(:charity_id, Charity.all, :id, :name) %>
    <%= f.collection_select(:group_id, Group.all, :id, :name) %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<strong> Edit a Challenge</strong>

<%= render("form") %>

app/views/challenges/index.html.erb
<h1>All Challenges</h1>

<table>
  <thead>
    <tr>
      <th><h2>Challenge Name </h2></th>
     
      
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= link_to(challenge.name, challenge_path(challenge)) %></td>
      
       
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to('Add a Challenge', new_challenge_path) %></h2>

app/views/challenges/new.html.erb
<strong> Add a NEW Challenge</strong>

<%= render("form") %>

app/views/challenges/show.html.erb
<h1><%= @challenge.name %></h1>
<p>
<strong>Charity Name: <%= link_to(@challenge.charity.name, charity_path(@challenge.charity)) %></strong>
</p>



<p>
  <strong>Activity:</strong>
  <%= @challenge.activity %>
</p>

<p>
<strong>Goal Activity Reps</strong>
<%= @challenge.activity_reps %>
</p>

<p>
  <strong>Challenge Start-Date: </strong>
  <%= @challenge.start_date %>
</p>

<p>
  <strong>Challenge End-Date: </strong>
  <%= @challenge.end_date %>
</p>

<p>
  <strong>Challenge Group: </strong>
  <%= link_to(@challenge.group.name, group_path(@challenge.group)) %>
<ul>
<strong>Particpating Members: </strong> 
  <% @challenge.group.users.each do |user| %>
    <li><%= link_to(user.name, user_path(user)) %></li>
  <% end %>
</ul>
</p>
<br>
<br>


<h2>Challenge Trackers<h2>
<table class="ctable" style="margin-left: 50px;">
  <tr>
    <th><h2>Name</h2></th>
    <th><h2>Day of the Week</h2></th> 
    <th><h2>Reps</h2></th>
  </tr>
  <% @challenge.activity_trackers.each do | tracker | %>
    <tr>
      <td><%= tracker.user.name %></td>
      <td><%= tracker.day %></td>
      <td><%= tracker.user_reps %></td>
    </tr>
  <% end %>
</table>




<br>
<br>
<br>

<h2><%= link_to('All challenges', challenges_path) %> |


<%= link_to("Edit", edit_challenge_path(@challenge)) %></h2>